export default {
  portrait1: require('./portrait/1.webp'),
  portrait2: require('./portrait/2.webp'),
  portrait3: require('./portrait/3.webp'),
  events1: require('./events/1.webp'),
  events2: require('./events/2.webp'),
  events3: require('./events/3.webp'),
  events4: require('./events/4.webp'),
  events5: require('./events/5.webp'),
  events6: require('./events/6.webp'),
  partners1: require('./partners/1.webp'),
  partners2: require('./partners/2.webp'),
  partners3: require('./partners/3.webp'),
  partners4: require('./partners/4.webp'),
};
